### ISSUE TITLE
開発準備

### ISSUE THREAD

**Issue by nokoxxx1212** [nokoxxx1212/keiba-hacke#1]
## 🧑 Story

- これから開発していくために、開発準備をする

## 🔨 Acceptance Criteria

- 開発に着手可能な状態であること。後はコードを書くだけの状態であること。

## 📝 Task List

- [x] ドキュメント管理ツールの整備
- [x] チケット管理ツールの整備
- [x] 会議体の整備
- [x] リポジトリの整備
- [x] 開発規約の整備
- [x] 初期コード配置、CI/CD設定、開発環境構築手順作成
    - [x] Python環境構築
        - [x] VSCode
        - [x] CICD
    - [x] Terraform環境構築
        - [x] VSCode
        - [x] Terraform Cloud
        - [x] CICD

## 📚 Resources

- [内製プラットフォーム開発に着手するまでに準備したこと（ドキュメント・チケット・開発規約、etc）](https://qiita.com/nokoxxx1212/items/b3f01f68e0d383476314)

## 🎯 Deliverables

- Code
- [内製プラットフォーム開発に着手するまでに準備したこと（ドキュメント・チケット・開発規約、etc）](https://qiita.com/nokoxxx1212/items/b3f01f68e0d383476314)
- [python-setup](https://github.com/nokoxxx1212/python-setup)

## 🔜 Remaining Tasks
- [x] Variablesをファイル管理（比較のため）

**Comment by nokoxxx1212** [comment]
### PythonのCIが動くようにする

- .github/workflows/python-app.yml書いてCI実行する
- →Error response from daemon: No such image: python312docker
- buildをコマンドじゃなく下記にする

```yaml
- name: Build and test Docker image
      uses: docker/build-push-action@v2
      with:
        context: app
        file: app/Dockerfile
        platforms: linux/amd64
        push: false
        tags: python312docker
```

- →Unable to find image 'python312docker:latest' locally docker: Error response from daemon: pull access denied for python312docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
- DockerHubを利用する
    - ${{ secrets.DOCKER_USERNAME }} Settingsを利用
- →Unable to find image '***/python312docker:latest' locally docker: Error response from daemon: manifest for ***/python312docker:latest not found: manifest unknown: manifest unknown.
- 変数でなく、直接書く
- →ERROR: file or directory not found: src
- srcをmntするようにrunコマンドを変更
    - ToDo: 開発はmntが良いが、本番はイメージに含めるしかないのでは
- →poetry run pytest /opt/mnt/src /opt/mnt/testが no tests ran in 0.00s Error: Process completed with exit code 5. でエラー
- workディレクトリを確認、パスを確認（パスがずれている）　←ToDo: そもそも、ローカルで実行する手順をReadmeにまとめる
- →ModuleNotFoundError: No module named 'src’
- sys appendしてみる
- poetry run pytest /opt/mnt/src /opt/mnt/testsはOKだった。appendしなくても成功する
- poetry install
